[package]
name = "teacup"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9"
prost-types = "0.9"
systemstat = "0.1.10"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
prost-build = { version = "0.9" }
