version: 3

dotenv:
  - ".env"

tasks:
  server:
    desc: Start the server receiving data
    env:
      TEACUP_DB_USER: teacup
      TEACUP_DB_PW: teacup
    cmds:
      - cargo run --bin server

  client:
    desc: Start the client sending telemetry
    env:
      TEACUP_TOKEN: pewpew
    cmds:
      - cargo run --bin client

  setup-db:
    desc: Runs the database migration scripts such as creating tables
    dir: server
    cmds:
      # allow longer timeout since by default 10 is a bit short for docker
      - sqlx database create --connect-timeout 30
      - sqlx migrate run

  start-localsetup:
    desc: Setup the local environment
    cmds:
      - docker-compose up -d
      - task: setup-db

  stop-localsetup:
    desc: Stop the local environment
    cmds:
      - docker-compose down
      - docker volume rm teacup_teacup-db-data
